services:
  backend:
    build: ./backend/transfermarkt-analyst
    ports:
      - "8080:8080"
    container_name: transfermarkt-backend
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    container_name: transfermarkt-frontend
    depends_on:
      - backend